os: Windows Server 2012

environment:
  VisualStudioVersion: 12.0
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

configuration: Release

before_build:
  - nuget restore src\psbuild.sln

build_script:
  - ps: .\appveyor.ps1

artifacts:
  - path: OutputRoot\**\*.ps*1
  - path: OutputRoot\PSBuild\**\*.dll
  - path: OutputRoot\PSBuild\**\*.pdb
  - path: OutputRoot\**\*.nupkg
  - path: \Users\appveyor\AppData\Local\LigerShark\PSBuild\logs\printprops.proj-log\*.log
